version: '3'

services:
  playlistmatesapi:
    container_name: playlistmatesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    depends_on:
    - postgres
    environment:
      - DATABASE_HOST=postgresdb

  playlistmatesclient:
    container_name: playlistmatesclient
    build:
      context: ./PlaylistMates.Client
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    depends_on:
    - playlistmatesapi
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      
  postgres:
    container_name: postgres
    build:
        context: ./docker/postgres
        dockerfile: Dockerfile
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - ./docker/postgres/data:/var/lib/postgresql/data

  #oracledb:
  #  build:
  #    context: ./docker/oracle
  #    dockerfile: Dockerfile
  #  ports:
  #  - 1521:1521
  #  environment:
  #  - ORACLE_PASSWORD=password
  #  volumes:
  #  - ./docker/oracle/data:/opt/oracle/oradata
    
