CREATE USER pos WITH PASSWORD 'pos';
ALTER ROLE pos SUPERUSER;
GRANT USAGE, CREATE ON SCHEMA public TO pos;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pos;
ALTER USER pos SET search_path TO public;